name: Link Checker (Kmart)

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at 12 AM

jobs:
  link_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'  # Adjust if needed

      - name: Install dependencies
        run: |
          python -m pip install requests beautifulsoup4 urllib3 concurrent.futures logging

      - name: Run the Python script
        run: |
          python aulinkcheck.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: link_check_results
          path: |
            verified_failed_links.txt

      - name: Send email notification
        uses: actions/send-mail@v3
        with:
          to: kiran.sahoo@kmart.com.au  # Replace with your email address
          subject: Kmart Link Check Results ({{ github.run_id }})
          body: |
            Check log file (link_check_log.txt) for details.
            Verified failed links (verified_failed_links.txt) might require further investigation.
